<?php

namespace asudre\CDM14Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquipesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipesRepository extends EntityRepository
{
	
	/**
	 * Sauvgarde des équipes à partir d'un tableau contenant le nom, pays et groupe. Ex : A['Bresil']
	 * @param unknown $tabEquipes
	 */
	function sauvegardeEquipesParGroupe($tabEquipes) {
		foreach ($tabEquipes as $gr => $eq)
		{
			foreach ($eq as $id => $nom) {
				// Création de l'entité
				$equipes = new Equipes();
				$equipes->setNom($nom);
				$equipes->setPays($nom);
				$equipes->setGroupe($gr);
		
				// Étape 1 : On « persiste » l'entité
				$this->_em->persist($equipes);
			}
		}
		
		// Étape 2 : On « flush » tout ce qui a été persisté avant
		$this->_em->flush();
		
		return 1;
	}
	
	/**
	 * Sauvegarde des équipes à partir des équipes par défaut
	 * @param unknown $equipes
	 */
	function sauvegardeEquipes($equipes) {

		foreach ($equipes as $eq)
		{
			// Étape 1 : On « persiste » l'entité
			$this->_em->persist($eq);
		}
		
		// Étape 2 : On « flush » tout ce qui a été persisté avant
		$this->_em->flush();
		
		return 1;
	}
	
	/**
	 * Récupère l'ensemble des équipes de la table
	 */
	function getEquipes() {
		return $equipes = $this->findAll();
	}
	
	/**
	 * Supprime toutes les équipes
	 */
	function supprimerToutes() {
		// Supprime toutes les valeurs de la table Equipes
		$query = $this->_em->createQuery('DELETE FROM asudreCDM14Bundle:Equipes a');
		return $query->execute();
	}
	
	/**
	 * Crée les nouvelles équipes à vide qui seront remplies par la suite
	 * @param unknown $nbEquipesParGroupe
	 * @param unknown $nbGroupes
	 * @return number
	 */
	function creationEquipesAVide($nbEquipesParGroupe, $nbGroupes) {
		$alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
		
		for ($i = 0; $i < $nbGroupes; $i++) {
			for ($j = 0; $j < $nbEquipesParGroupe; $j++) {
				// Création de l'entité
				$equipes = new Equipes();
				$equipes->setNom('');
				$equipes->setPays('');
				$equipes->setGroupe($alphabet[$i]);
		
				// Étape 1 : On « persiste » l'entité
				$this->_em->persist($equipes);
			}
		}
		
		// Étape 2 : On « flush » tout ce qui a été persisté avant
		$this->_em->flush();
		
		return 1;
	}
	
	/**
	 * Récupération du nombre d'équipes et de groupe sauvegardés en base
	 */
	function getNombreEquipesetGroupes() {
		$query = $this->_em->createQuery('SELECT count(a), count(distinct a.groupe) FROM asudreCDM14Bundle:Equipes a');
		return $query->getScalarResult();
	}
	
	/**
	 * Récupération des équipes ordonnées par groupes
	 */
	function getEquipesOrdGroupes() {
		$query = $this->createQueryBuilder('a');
		$query->orderBy('a.groupe', 'ASC');
		return $query->getQuery()->getResult();
	}
	
	/**
	 * Récupération de l'équipe
	 * @param unknown $idEquipe
	 */
	function getEquipe($idEquipe) {
		$query = $this->_em->createQuery('SELECT a FROM asudreCDM14Bundle:Equipes a WHERE a.id = :equipe');
		$query->setParameters(array(
				'equipe' => $idEquipe
		));
		
		return $query->getResult();
	}
}
