<?php

namespace asudre\CDM14Bundle\Entity;

use Doctrine\ORM\EntityRepository;
use asudre\CDM14Bundle\Entity\Mises;

/**
 * MisesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MisesRepository extends EntityRepository
{
	public function ajoutMise($utilisateur, $equipe, $match, $valeur) {
		
		$mise = new Mises();
		$mise->setValeur($valeur);
		$mise->setDate(new \DateTime("now"));
		$mise->setUtilisateur($utilisateur);
		$mise->setEquipe($equipe);
		$mise->setMatch($match);
		
		$this->_em->persist($mise);
		$this->_em->flush();

		return Mises::OK;
	}

	/**
	 * Récupère l'ensemble des mises d'un match
	 * @param unknown $idMatch
	 */
	public function getMisesMatch($idMatch) {
		$query = $this->_em->createQuery('SELECT a FROM asudreCDM14Bundle:Mises a WHERE a.match = :match');
		$query->setParameters(array(
			'match' => $idMatch
		));

		return $query->getResult();
	}
	

	/**
	 * Récupère l'ensemble des mises d'un utilisateur
	 * @param unknown $idUtilisateur
	 */
	public function getMisesUtilisateur($idUtilisateur) {
		$query = $this->_em->createQuery('SELECT a FROM asudreCDM14Bundle:Mises a WHERE a.utilisateur = :utilisateur order by a.match, a.date desc');
		$query->setParameters(array(
				'utilisateur' => $idUtilisateur
		));
	
		return $query->getResult();
	}
	
	/**
	 * Récupération de la somme des mises d'un utilisateur dont les matchs ne sont pas joués
	 */
	public function getSommeMises($idUtilisateur) {
		$query = $this->_em->createQuery('SELECT sum(m.valeur) as total from asudreCDM14Bundle:Mises m
				LEFT JOIN asudreCDM14Bundle:Historique h 
				WITH m.utilisateur = h.utilisateur AND m.match = h.match
				WHERE m.utilisateur = :id and h.id IS NULL');
		$query->setParameters(array(
				'id' => $idUtilisateur
		));
	
		return $query->getScalarResult();

	}
}
