parameters:
#    asudre_utilisateurs.example.class: asudre\UtilisateursBundle\Example

services:
#    asudre_utilisateurs.example:
#        class: %asudre_utilisateurs.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
